### ISSUE TITLE
Issue related to Crunchy Postgressql Database backup

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#1012]
Issue related to Crunchy Postgressql Database:

> I am back with another low-priority issue about object storage and the Crunchy PGO. Perhaps I should first ask: are object storage and Crunchy PGO features of NERC-OCP which the team has the bandwidth for and are interested in maintaining? If not, we can easily use alternative solutions (e.g. use bitnami/postgresql instead of Crunchy PGO, and PersistentVolumeClaim instead of object storage).
> 
> Back to the actual issue: can you help me debug this "UnableToCreateStanzas" error when using Crunchy PGO and S3 backups? I tried using OpenStack Swift object storage and OpenShift NooBaa object storage but it seems like both give the same error.
> 
> I created a Swift Object Storage bucket and generated credentials for it. Then I created a PostgresCluster:
> 

```
kind: PostgresCluster
apiVersion: postgres-operator.crunchydata.com/v1beta1
metadata:
  name: pg-try-swift-backup
  namespace: chris-3114b1
spec:
  postgresVersion: 16
  users:
    - name: chris
      databases: [ chris ]
    - name: authentik
      databases: [ authentik ]
  instances:
    - name: instance1
      replicas: 1
      resources:
        requests: &REQUESTS
          cpu: 250m
          memory: 1Gi
        limits: *REQUESTS
      dataVolumeClaimSpec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: nerc-openstack-ec2
      global:
        repo1-path: /pgbackrest/postgres-operator/blt/repo1

        # retain full backups for 14 days
        repo1-retention-full: "14"
        repo1-retention-full-type: "time"
      repos:
        - name: repo1
          schedules:
            full: "0-59/5 * * * *"     # every 5 minutes
            differential: "* * * * *"  # every minute
          s3:
            bucket: blt-trial-pgbackup
            endpoint: https://stack.nerc.mghpcc.org/:13808
            region: ""
```

> Unfortunately, the backups do not work. I get this event:

`Warning UnableToCreateStanzas 79s (x9 over 2m52s) postgrescluster-controller command terminated with exit code 32:`

> I don't know how to debug the "postgrescluster-controller command" (it might be something that runs in the operator's namespace instead of my project's namespace).
