### ISSUE TITLE
Grant vllm-d group cluster admin access to exeter cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#1095]
We need to grant the `vllm-d` group cluster-admin access on the exeter cluster. I've manually applied the following clusterrolebinding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: llm-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: vllm-d
```

I wasn't sure if there's a config repository behind this (there doesn't appear to be an overlay [here](https://github.com/OCP-on-NERC/nerc-ocp-config)).
