### ISSUE TITLE
Configure storage for prometheus on infra cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#129]
We haven't previously configured storage for Prometheus on the infra cluster, which means that the Prometheus pods are using ephemeral storage for metrics data. This means we lose recent metrics whenever the pods are restarted.

We should set the `volumeClaimTemplate` section of the monitoring configuration as we have for the prod cluster.

It looks like the observability stack has made some changes to the cluster monitoring configuration, so we will need to preserve those as well. This is the current configuration in the `cluster-monitoring-config` configmap:

```
alertmanagerMain: null
enableUserWorkload: null
grafana: null
http: null
k8sPrometheusAdapter: null
kubeStateMetrics: null
openshiftStateMetrics: null
prometheusK8s:
  additionalAlertmanagerConfigs:
  - apiVersion: v2
    bearerToken:
      key: token
      name: observability-alertmanager-accessor
    pathPrefix: /
    scheme: https
    staticConfigs:
    - alertmanager-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu
    tlsConfig:
      ca:
        key: service-ca.crt
        name: hub-alertmanager-router-ca
      insecureSkipVerify: false
  externalLabels:
    managed_cluster: b3c6e302-f119-4adb-bc48-e04c6aa2eaa5
  logLevel: ""
  nodeSelector: null
  queryLogFile: ""
  remoteWrite: null
  resources: null
  retention: ""
  tolerations: null
  volumeClaimTemplate: null
prometheusOperator: null
telemeterClient: null
thanosQuerier: null
```
