### ISSUE TITLE
Should we be using Red Hat provided cert-manager operator?

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#215]
@computate points out that we're using the upstream cert-manager operator rather than the Red Hat supported one. Should we look at moving to the Red Hat operator? We need to ensure it doesn't represent a significant version change.

**Comment by computate** [comment]
@larsks I have also been researching and troubleshooting using our upstream version of cert-manager. I learned that cert-manager will never support the automatic creation of Lets Encrypt certificates for Routes, [see the last comment in this PR that was rejected](https://github.com/cert-manager/cert-manager/pull/2840#issuecomment-729561751) with three complaints around functionality, vendoring, and security within cert-manager. 

However, the automatic creation of Lets Encrypt certificates is supported for Ingress objects, but when I set up an Issuer see: 
```
oc --as system:admin -n software-application-innovation-lab-sail-projects-fcd6dfa get Issuer
```

and an Ingress that relates to the Issuer: 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecology
  namespace: software-application-innovation-lab-sail-projects-fcd6dfa
  annotations:
    cert-manager.io/issuer: letsencrypt-issuer
    acme.cert-manager.io/http01-ingress-class: openshift-default 
spec:
  ingressClassName: openshift-default
  tls:
  - hosts:
    - ecology.computate.org
    secretName: ecology-ingress
  rules:
  - host: ecology.computate.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pecan-web
            port:
              number: 8888
```

Then there is an error that occurs in the cert-manager pods: 

E0831 13:27:56.366895       1 controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="pods \"cm-acme-http-solver-w7vd8\" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations.seccomp.security.alpha.kubernetes.io/pod: Forbidden: seccomp may not be set pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/acmesolver: Forbidden: seccomp may not be set provider \"anyuid\": Forbidden: not usable by user or serviceaccount provider \"pipelines-scc\": Forbidden: not usable by user or serviceaccount provider \"nonroot\": Forbidden: not usable by user or serviceaccount provider \"noobaa\": Forbidden: not usable by user or serviceaccount provider \"noobaa-endpoint\": Forbidden: not usable by user or serviceaccount provider \"hostmount-anyuid\": Forbidden: not usable by user or serviceaccount provider \"log-collector-scc\": Forbidden: not usable by user or serviceaccount provider \"machine-api-termination-handler\": Forbidden: not usable by user or serviceaccount provider \"hostnetwork\": Forbidden: not usable by user or serviceaccount provider \"hostaccess\": Forbidden: not usable by user or serviceaccount provider \"rook-ceph\": Forbidden: not usable by user or serviceaccount provider \"node-exporter\": Forbidden: not usable by user or serviceaccount provider \"rook-ceph-csi\": Forbidden: not usable by user or serviceaccount provider \"privileged\": Forbidden: not usable by user or serviceaccount]" key="software-application-innovation-lab-sail-projects-fcd6dfa/ecology-ingress-6jvhw-4058851002-1768250778"

It seems that additional SecurityContextConstraints are required in OpenShift `4.10` to use this functionality of the upstream cert-manager. This might work better with the official cert-manager Operator for Red Hat OpenShift, but it might be hard to test this in the test cluster if it's behind the VPN. 

I tested this with my OpenShift Local environment running OpenShift `4.12.5` with the official cert-manager Operator for Red Hat OpenShift, and it seems to work better, but can't reach the DNS because it's a private virtual machine I think: 

E0830 19:57:04.754878       1 sync.go:190] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://test-crc.smartabyarsmartvillage.org/.well-known/acme-challenge/mI7g19u2DxqzUJahz6t0W6cQ_cZE1ldEgZF6gBtfHg4': Get \"http://test-crc.smartabyarsmartvillage.org/.well-known/acme-challenge/mI7g19u2DxqzUJahz6t0W6cQ_cZE1ldEgZF6gBtfHg4\": dial tcp: lookup test-crc.smartabyarsmartvillage.org on 10.217.4.10:53: no such host" "dnsName"="test-crc.smartabyarsmartvillage.org" "resource_kind"="Challenge" "resource_name"="test-crc-ingress-pzf6v-3009109852-611605574" "resource_namespace"="smartvillage" "resource_version"="v1" "type"="HTTP-01"
