### ISSUE TITLE
Create sample R-Studio Shiny app in OpenShift AI/RHODS

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#292]
Show it's possible to develop applications and run them directly in an OpenShift AI like an [R-Studio Shiny app](https://www.rstudio.com/products/shiny/) with this [RStudio OpenShift AI image here](https://github.com/opendatahub-io-contrib/workbench-images).

**Comment by computate** [comment]
@hpdempsey  I can run a R Shiny script in RHODS NERC with the [RStudio image provided by opendatahub] that connects to a port `12080` that I configured in the application like this:

```R
shiny::runApp(host = '0.0.0.0', port=12080, app=app)
```

But RHODS will not let me expose a custom port `12080` to create a Service and Route to expose the running R Shiny app. It's best to build this into a container image with podman, deploy it to [quay.io](http://quay.io/), and create a separate Deployment to run this R Shiny application. It would be nice if RHODS would let you add additional ports to your workbook in addition to storage and environment variables which it provides.

If I remove the labels that manage my R-Studio RHODS workbench for ecological forecasting, I can add an extra port and serve up a sample R Shiny app from a custom port running live in my workbench in the browser, as shown here:

![image](https://github.com/nerc-project/operations/assets/15114160/55b92ede-4339-407a-94e1-3d402d1a4f8f)

![image](https://github.com/nerc-project/operations/assets/15114160/628ca478-4415-46cd-9212-3ae556c14dfa)

RHODS automatically adds labels like this to a StatefulSet which creates the pod for a RHODS workbench:

```yaml
      labels:
        app: ctate-rhods-pecan
        notebook-name: ctate-rhods-pecan
        opendatahub.io/dashboard: 'true'
        opendatahub.io/odh-managed: 'true'
        opendatahub.io/user: ctate-40redhat-2ecom
        statefulset: ctate-rhods-pecan
```

If I try to add a port in my StatefulSet so that I could expose the application to show you the UI, I can't because RHODS automatically reverts my changes to add a pod. If I simplify the labels in my StatefulSet, which I have edit privileges to do in my namespace:

```yaml
      labels:
        app: ctate-rhods-pecan
        statefulset: ctate-rhods-pecan
```

The StatefulSet is no longer managed by opendatahub (RHODS). After creating a Service and a Route that points to that port, then it becomes available from my route -> service -> pod. Unfortunately, if I look at RHODS, it doesn't look happy anymore: 

![image](https://github.com/nerc-project/operations/assets/15114160/58ca0f75-4d0b-4be0-bcd6-eca275f2353f)

RHODS only opens up the jupyter notebook GUI port 8888 which is only internal, as well as an OAuth Proxy service which exposes it to the user, only after authenticating to OpenShift first. If we could add any port to a RHODS workbench, then it would be super user friendly to develop and run live code directly within any RHODS image.

**Comment by joachimweyl** [comment]
@computate what are the next steps for this?

**Comment by computate** [comment]
@larsks do we know how to create a feature request for the OpenShift AI team to add custom ports to workbenches?

**Comment by larsks** [comment]
> I'm not sure if Lars has credentials for a "customer" feature request on behalf of BU as he does for OpenShift

I'm not sure that I have any special privileges for feature requests for OpenShift either. I can make requests as part of a support case (which is what we recommend in https://access.redhat.com/solutions/73513); we could do the same thing for openshift AI.

It's also possible to directly create an RFE in Jira at https://issues.redhat.com/ (which I *think* anybody can do), probably in the RHODS project, but we should probably ask in the forum whether or not this is kosher.

**Comment by larsks** [comment]
@computate

> If I try to add a port in my StatefulSet so that I could expose the application to show you the UI...

You shouldn't need to modify the StatefulSet. You can create a Service for a port in a container regardless of whether or not it is explicitly exposed in the `ports` section of the container spec.

Take a look at the example in <https://github.com/larsks/example-expose-without-port>. We start with a Deployment like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: docker.io/traefik/whoami:latest
        name: whoami
        env:
          - name: WHOAMI_PORT_NUMBER
            value: "8080"
```

Note that there is `ports` specification here. That doesn't prevent us from creating a Service:

```
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 8080
```

And exposing it via a Route:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: web
```

With all that in place:

```
$ curl web-example-for-computate.apps.shift.nerc.mghpcc.org
Hostname: web-5bc6cd699d-hth98
IP: 127.0.0.1
IP: ::1
IP: 10.130.0.57
IP: fe80::488d:fdff:fe18:cf05
RemoteAddr: 10.129.10.1:45932
GET / HTTP/1.1
Host: web-example-for-computate.apps.shift.nerc.mghpcc.org
User-Agent: curl/8.0.1
Accept: */*
Forwarded: for=108.7.73.199;host=web-example-for-computate.apps.shift.nerc.mghpcc.org;proto=http
X-Forwarded-For: 108.7.73.199
X-Forwarded-Host: web-example-for-computate.apps.shift.nerc.mghpcc.org
X-Forwarded-Port: 80
X-Forwarded-Proto: http
```

**Comment by computate** [comment]
@larsks unfortunately the typical Route and Service approach doesn't work with our OpenShift AI containers, because they have more than one container in the pod, and seems to by default route to the `oauth-proxy` container instead of the application container where the port 8080 is defined. See a running RShiny app running on port 8080 here in the prod cluster: 

```bash
oc -n software-application-innovation-lab-sail-projects-fcd6dfa \
  exec $(oc -n software-application-innovation-lab-sail-projects-fcd6dfa get pod -l app=ctate-rhods-pecan -o name) \
  -- curl http://localhost:8080
```

But the following Service and Route do not serve up port 8080: 

```bash
oc -n software-application-innovation-lab-sail-projects-fcd6dfa get svc/rshiny-ctate
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
rshiny-ctate   ClusterIP   172.30.53.158   <none>        8080/TCP   26d

oc -n software-application-innovation-lab-sail-projects-fcd6dfa get route/a
NAME   HOST/PORT                                                                                PATH   SERVICES       PORT   TERMINATION   WILDCARD
a      a-software-application-innovation-lab-sail-projects-fcd6dfa.apps.shift.nerc.mghpcc.org          rshiny-ctate   8080   edge          None
```

**Comment by larsks** [comment]
>  seems to by default route to the oauth-proxy container instead of the application container where the port 8080 is defined

Ports are open on the *pod*, not in individual containers (because all containers in the pod run in the same network namespace). If something is listening on port 8080, that port is bound in all containers.

Let me take a closer look at the specific example.

Incidentally, instead of:

```
oc  -n software-application-innovation-lab-sail-projects-fcd6dfa   exec $(oc -n software-application-innovation-lab-sail-projects-fcd6dfa get pod -l app=ctate-rhods-pecan -o name)   -- curl http://localhost:8080
```

You can save yourself some typing and write:

```
oc  -n software-application-innovation-lab-sail-projects-fcd6dfa   exec statefulset/ctate-rhods-pecan -- curl http://localhost:8080
```

**Comment by larsks** [comment]
Just thinking out loud here, something doesn't make sense. The service is demonstrably working correctly. If we port forward the service:

```
kubectl port-forward svc/rshiny-ctate 8080:8080
```

Then `curl localhost:8080` works as expected when run on our local system.

**Comment by larsks** [comment]
It looks like RHODS creates a [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) that only permits access to specific ports:

```
$ k get netpol
NAME                           POD-SELECTOR                        AGE
ctate-rhods-pecan-ctrl-np      notebook-name=ctate-rhods-pecan     59d
ctate-rhods-pecan-oauth-np     notebook-name=ctate-rhods-pecan     59d
.
.
.
```

Where e.g. the policy `ctate-rhods-pecan-ctrl-np` looks like:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctate-rhods-pecan-ctrl-np
  namespace: software-application-innovation-lab-sail-projects-fcd6dfa
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: redhat-ods-applications
    ports:
    - port: 8888
      protocol: TCP
  podSelector:
    matchLabels:
      notebook-name: ctate-rhods-pecan
  policyTypes:
  - Ingress
```

We can open up all access to your container by creating a NetworkPolicy like this:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lars-test-netpol
  namespace: software-application-innovation-lab-sail-projects-fcd6dfa
spec:
  ingress:
    - ports:
      - port: 8080
        protocol: TCP
  podSelector:
    matchLabels:
      notebook-name: ctate-rhods-pecan
```

With this in place, your existing route will work as expected.

I'm deleting the above `lars-test-netpol` right now to avoid cluttering things up, but that means you'll need to deploy a new one before the Route works.

**Comment by larsks** [comment]
Unrelated to your question, but you can declare an explicit hostname for your route and it doesn't have to include the namespace name. So you could have:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: a
spec:
  host: rshiny-ctate.apps.shift.nerc.mghpcc.org
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: rshiny-ctate
```
