### ISSUE TITLE
Setup Metrics Gathering on the New Observability Cluster

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#326]
- subtask of https://github.com/nerc-project/operations/issues/177
- Zenhub Epic [```Setup a new Cluster to handle Metrics, Logging and Observability```](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzNzMy)

timeline: 2023/Q4 - 2024/Q1

right now catching this as an issue for #177

- [x] creating an idea diagram
- [x] How do we manage custom dashboards? https://github.com/nerc-project/operations/issues/54
- [x] monitoring components
- [x] define possible alerts

**Comment by computate** [comment]
@schwesig @jbasu01 Thanks @harshil-codes for the suggestion to follow the [documentation for configuring an external grafana to query metrics with the Observatorium API](https://www.redhat.com/en/blog/how-your-grafana-can-fetch-metrics-from-red-hat-advanced-cluster-management-observability-observatorium-and-thanos). After trying out the right secrets this time, I managed to get a temporary Grafana datasource like this working. This will allow us to set up Grafana on the observability cluster, but point it to the observatorium Route on the infra cluster. There is CA Cert validation and TLS Client auth that will allow the observability cluster to connect to the infra cluster. We just need to put the credentials in Vault. Here is how to configure the GrafanaDatasource: 

```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: observability-metrics
  namespace: grafana
  labels:
    app.kubernetes.io/instance: grafana-infra
spec:
  datasources:
    - access: proxy
      editable: false
      jsonData:
        timeInterval: 5s
        tlsAuth: true
        tlsAuthWithCACert: true
      name: observability-metrics
      secureJsonData:
        tlsClientCert: |-
          # Use `oc --as system:admin -n open-cluster-management-observability get secret/observability-grafana-certs -o jsonpath='{.data.tls\.crt}' | base64 -d`
        tlsClientKey: |-
          # Use `oc --as system:admin -n open-cluster-management-observability get secret/observability-grafana-certs -o jsonpath='{.data.tls\.key}' | base64 -d`
        tlsCACert: |-
          # Use `oc --as system:admin -n open-cluster-management-observability get secret/observability-server-ca-certs -o jsonpath='{.data.ca\.crt}' | base64 -d`
      type: prometheus
      url: >-
        https://observatorium-api-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/metrics/v1/default
  name: observability-metrics
```
