### ISSUE TITLE
Apply configurable retention to Observability Metrics

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#353]
As part of our updates to ACM Observability, we want to make sure that we apply the right [retention of metrics in ACM Observability based on our NERC Acceptance tests](https://github.com/OCP-on-NERC/docs/blob/main/acceptance-tests.md#data-management). We can follow the [Red Hat documentation for configuring Observability retention here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/observability/customizing-observability#adding-advanced-config). We can apply the retentionConfig to our [MultiClusterObservability config](https://github.com/OCP-on-NERC/nerc-ocp-config/blob/main/cluster-scope/base/observability.open-cluster-management.io/multiclusterobservabilities/observability/multiclusterobservability.yaml) on the infra cluster.

**Comment by schwesig** [comment]
@schwesig

**Comment by computate** [comment]
Based on a discussion about ACM Metrics retention, the default ACM Observability retention is defined here: 

```yaml
retentionResolutionRaw: 5d
retentionResolution5m: 14d
retentionResolution1h: 30d
```

@harshil-codes suggested we could set these values to 15d/30d/90d for our acceptance tests. 
```yaml
retentionResolutionRaw: 15d
retentionResolution5m: 30d
retentionResolution1h: 90d
```

We will also follow the [Red Hat recommended solution for Observability metrics backup](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/using-observability#exporting-metrics-to-external-endpoints) for a year's worth of metrics.
