### ISSUE TITLE
Create resourceQuota in rhods-notebooks namespace (Prod cluster)

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#377]
We need to create a resourceQuota in this namespace since there isn't one by default. 

We will need a pretty hefty quota since both ope courses are using the namespace. Since we can't limit the notebook resource options to the minimal allocation in rhods without removing them as options from all the users, we need to keep in mind that students technically have the ability to choose any of the allocation options for their notebook. 

We have in the [docs](https://massopencloud.slack.com/files/U04QKBPMUQ6/F06DJUR7GUA/how_to_launch_ucsls_jupyter_instance.pdf?origin_team=T14CVG7L1&origin_channel=CNMSRMDA5) specified the x-small resource option but we can't enforce this in our current setup. That makes it somewhat tricky to nail down an exact hard quota limit Since in the absolute worst case (incredibly unlikely but technically possible) all students could select other bigger options. 

 We ran the scale test in ope-rhods-testing with 300 instances and didn't hit our quota so maybe that's a good starting point. As for storage we can pretty comfortably set a limit once we know exactly the number of students we expect (all notebooks create a pvc with one Gi). 

We can use this as a starting point:
```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: spring-course-quota
  namespace: rhods-notebooks

spec:
  hard:
    limits.cpu: '1000'
    limits.ephemeral-storage: 50Gi
    limits.memory: 3000000Mi
    persistentvolumeclaims: '1000'
    requests.storage: 100Gi
```

We should run the test again with the expected number of students to see how it looks against something like the resourceQuota above.
