### ISSUE TITLE
SecretSyncedError in github-client-secret - infra and obs

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#381]
## Trigger
- obs.cluster, github-client-secret/clientSecret, external secrets
  - could not get secret data from provider (external-secrets, vault)
  - secret does not exists

```yaml
  conditions:
    - lastTransitionTime: '2024-01-15T11:36:04Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
      type: Ready
```

## Details
- first  guess, new configs in new obs.cluster are not correct
- check in infra showed same basic error
- infra.cluster
  - could not get secret data from provider (external-secrets, vault)
  - but secret exists, github-client-secret/clientSecret, created Jan 19, 2023, 5:14 PM
  
```yaml
conditions:
    - lastTransitionTime: '2024-01-15T07:17:13Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
```

## Problem
1. obs - current problem: can not authenticate via github at all
2. infra - future problem: when we lose current stored clientSecret (Jan 19, 2023), secret can not be recreated automatically
