### ISSUE TITLE
ClusterVersion on infra cluster has changed values for clusterId, channel, desiredUpdate.version

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#388]
After reverting the configuration of the `clientId` value of the `OAuth` configuration on the infra cluster, I noticed that the `ClusterVersion` was also updated to the wrong `clusterId`, `channel`, and `desiredUpdate.version`. The configured values for the [ClusterVersion in the infra cluster in GitHub are here](https://github.com/OCP-on-NERC/nerc-ocp-config/blob/main/cluster-scope/overlays/nerc-ocp-infra/clusterversion.yaml):  

```yaml
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.13
  desiredUpdate:
    version: 4.13.13
  clusterID: b3c6e302-f119-4adb-bc48-e04c6aa2eaa5
```

But the infra cluster currently has the wrong values for `clusterId`, `channel`, and `desiredUpdate.version`. Here are the current values: 

```bash
$ oc get clusterversion -o yaml | grep 'spec:' -A 4
  spec:
    channel: stable-4.14
    clusterID: 760c86f3-95a0-489e-b72a-2938bb80bcea
    desiredUpdate:
      version: 4.14.5
```

These values will need to be reverted, probably with a sync from ArgoCD. Fortunately, [you can see here that the cluster did not upgrade to 4.14](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/settings/cluster). It says "Invalid cluster version", and "This cluster should not be updated to the next minor version. Kubernetes 1.27 and therefore OpenShift 4.14 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/6958395 for details and instructions."Could be related to [this PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/337/files) being partially applied by mistake with these values configured for the obs cluster. Changes to the `ClusterVersion` and `OAuth` in this PR were applied by mistake, but not the ExternalSecrets, they still point to the infra cluster.
