### ISSUE TITLE
Design and create new repo to store rates and invoicing policy changes

### ISSUE THREAD

**Issue by knikolla** [nerc-project/operations#420]
Motivation
- Inputting rate values is a manual process and requires checking and copying the values from the NERC website.
- It makes it hard to track which rates are effective for which period of time. eg. price of A100 SU.
- It's hard to track which policy changes are effective from which date. eg. When to start charging for stopped instances.
- Can't plan changes in value ahead of time.

I propose the creation of a repository `nerc-project/rates` to store the above missing information.

A possible representation of that information may be (using YAML):

```yaml
serviceUnitTypes:
  - name: OpenStack CPU
    resources: NERC OpenStack
    specifications:
      - memory: 4096
        vcpus: 1
        startDate: 2022-01-01
    rates:
      - rate: 1.13
        startDate: 2024-01-01
      - rate: 1.12
        startDate: 2023-01-01
        endDate: 2023-12-1

  - name: OpenStack GPUA100
    resources: NERC OpenStack
    specifications:
      - startDate: 2023-01-01
        pciDeviceName: A100
    rates:
      - rate: 100.13
        startDate: 2023-01-01

invoicingPolicies:
  - name: Charge for Stopped Instances
    resources: NERC OpenStack
    values:
      - value: True
        startDate: 2024-05-01
      - value: False
        startDate: 2023-01-01
        endDate: 2024-04-31

```
