### ISSUE TITLE
Requesting ACM Metrics Endpoint Access from the Prod Cluster

### ISSUE THREAD

**Issue by Zongshun96** [nerc-project/operations#453]
Hi All,
We are from the ai4cloudops team that has used the test cluster for our project for the past months. As the test cluster is decommissioning, we are transitioning our [Praxi-Pipeline](https://github.com/ai4cloudops/Praxi-Pipeline) project to the prod cluster. The project focuses on discovering packages in active containers for cloud operation tasks, e.g., vulnerable package detection.

Our pipeline retrieves running container data from the ACM observability, which requires access permissions within the prod cluster. Following @dystewart and @computate's suggestions, we create this issue asking for help to set up the necessary permissions to access the ACM endpoint from the prod cluster.

Thanks,
Zongshun

**Comment by computate** [comment]
Thanks for reaching out @Zongshun96 . Do you have a project/namespace in NERC Prod OpenShift where you expect your application to run that will connect to the metrics?

**Comment by computate** [comment]
@larsks @schwesig  @hpdempsey Do you have any concerns if we create a secret in the namespaces for AI4CloudOps in prod to connect to ACM Observability observatorium metrics on the infra cluster? 

We use a ClusterRoleBinding for the `grafana-serviceaccount` token and `cluster-monitoring-view` ClusterRole on Infra, and the following certificates for this secret for AI4CloudOps to connect to ACM Observability observatorium metrics: 

```yaml
stringData:
  token: |-
    # Use `oc --as system:admin -n grafana get secret/grafana-serviceaccount-token -o jsonpath={.data.token} | base64 -d`
  tlsClientCert: |-
    # Use `oc --as system:admin -n open-cluster-management-observability get secret/observability-grafana-certs -o jsonpath='{.data.tls\.crt}' | base64 -d`
  tlsClientKey: |-
    # Use `oc --as system:admin -n open-cluster-management-observability get secret/observability-grafana-certs -o jsonpath='{.data.tls\.key}' | base64 -d`
  tlsCACert: |-
    # Use `oc --as system:admin -n open-cluster-management-observability get secret/observability-server-ca-certs -o jsonpath='{.data.ca\.crt}' | base64 -d`
```
