### ISSUE TITLE
How do we manage custom dashboards?

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#54]
If we create custom dashboards, how do we save those configurations so that they are not lost in the even of a cluster rebuild or grafana reinstall? Can we store them in a git repository and have them deployed automatically?

includes
@jbasu01
@harshil-codes

**Comment by computate** [comment]
We want to be able to create the custom dashboards defined [here in the ACM docs](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/observability/observing-environments-intro#setting-up-the-grafana-developer-instance), but as infrastructure as code in the nerc-ocp-config repo.

**Comment by computate** [comment]
We want to include the `OpenShift Logging Collection` dashboard from the default Observe -> Dashboards in OpenShift for logging performance.

**Comment by computate** [comment]
@harshilcodes suggested we use the [dashboard configmaps](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/openshift-config-managed/core~v1~ConfigMap?name=dashboard) in `openshift-config-managed` namespace to build our custom dashbaords in ACM. We need to make sure it can handle multiple clusters instead of local-cluster.

**Comment by computate** [comment]
@jbasu01 @harshil-codes  We will want to add back [this grafana directory] to nerc-ocp-config, but move the Grafana instance into a different namespace besides `openshift-logging`. 

- Instead of a grafana/base/loki-datasource.yaml, we will want a different one that looks like this: 

```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  namespace: ...
spec:
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer ...
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/'
  name: custom-observability-grafana
```
We will need to handle the Bearer token special, like in our Vault. 

- We also need to [add a ClusterRoleBinding as documented here](https://access.redhat.com/solutions/5335491): 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-serviceaccount-cluster-monitoring-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: ...
```
