### ISSUE TITLE
What should the minimum cpu or memory request be?

### ISSUE THREAD

**Issue by naved001** [nerc-project/operations#602]
All user namespaces have a limitrange that set default limits and requests for cpu and memory if the pod spec does not specify it.

However, one could specifically request 0 cpu and/or memory and the pod will be scheduled. This means that for billing purposes it will not be captured because the pod requested 0 resources; but in reality as long as the cluster has resources it'll continue to run and consume up to the limit specified (either in pod spec or from the default limitrange).

This came up when I was examining a pod that wasn't captured in the invoice with the following specs:

```
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
        nvidia.com/gpu: "0"
      requests:
        memory: "0"
        nvidia.com/gpu: "0"
```

Once the cluster has higher utilization then it may become a moot point because a pod like this would be the first to get kicked out. I believe this user did this by mistake and maybe we should reach out to them? They had hundreds of pods in state "UnexpectedAdmissionError" before they got a running one.
