### ISSUE TITLE
 test-2: Finalizing NNCP to ensure network settings persist after reboot, exploring DHCP options for a scalable solution

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#679]
## Motivation
follow up from
- https://github.com/nerc-project/operations/issues/674
- trigger: kruize GPU project
- on test-2 https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org/

To ensure that network settings persist after reboots on the GPU node, explore DHCP options for a more scalable solution.
This will prevent network configuration issues and improve the system's reliability.

## Completion Criteria
- Creation and implementation of a NodeNetworkConfigurationPolicy (NNCP) to ensure network settings persist after reboots.
- Evaluation and implementation of DHCP options for a more scalable network configuration solution.

## Description
- [ ] Finalize and test the NodeNetworkConfigurationPolicy (NNCP) to ensure VLAN interface and routing settings persist after reboots.
- [ ] Explore and document DHCP options for the network configuration.
- [ ] Implement the chosen DHCP solution, if applicable.
- [ ] Validate that the network settings are persistent and the DHCP solution works across reboots and node restarts.

## Completion dates
Desired - 2024-09-xx ?
Required - ?

/CC @tssala23 @dystewart @schwesig @naved001 @hakasapl

---

basic idea from
- https://github.com/nerc-project/operations/issues/674#issuecomment-2274002092
- slack: https://massopencloud.slack.com/archives/CG1C4SZCM/p1723051350335009?thread_ts=1722974917.195019&cid=CG1C4SZCM

```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-211
spec:
  nodeSelector:
    kubernetes.io/hostname: "wrk-5"
  desiredState:
    interfaces:
    - name: eno1np0.211
      type: vlan
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-routes: true
        address:
        - ip: 10.0.120.39
          prefix-length: 22
      vlan:
        base-iface: eno1np0
        id: 211
      mtu: 9000
    routes:
      config:
      - destination: 10.255.116.0/23
        next-hop-address: 10.0.120.1
        next-hop-interface: vlan-211
      - destination: 10.247.236.0/25
        next-hop-address: 10.0.120.1
        next-hop-interface: vlan-211
      - destination: 140.247.236.0/25
        next-hop-address: 10.0.120.1
        next-hop-interface: vlan-211
```
