### ISSUE TITLE
Fuse mounts for Matt

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#686]
Via @Milstein on slack:

> Hello,
> I'm attempting to get FUSE working in a pod to support mounting an s3 bucket. However, all references I can find point to running the pod in a privileged context, which gets denied.
> Here is my pod yaml:
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: ubuntu-pod
>   annotations:
>     io.kubernetes.cri-o.Devices: "/dev/fuse"
>   labels:
>     app: ubuntu
> spec:
>   containers:
>   - name: ubuntu-container
>     image: image-registry.openshift-image-registry.svc:5000/project-robbie-b4784c/mount-s3-test
>     command: ["sleep"]
>     args: ["infinity"]
>     resources:
>       limits:
>         memory: "128Mi"
>         cpu: "500m"
>     tty: true
>     stdin: true
>     securityContext:
>     runAsUser: 1001970001
>     privileged: true
> ```
>
> Without the privileged flag set, I get the following error attempting to mount the filesystem:
>
> ```
> mount-s3 --prefix mbrewster@collineargroup.com/0a3f1d18-ef8a-4379-8de5-b47094e99877/ positron-dev-workspaces ~/workspace
> fusermount: mount failed: Operation not permitted
> Error: Failed to create FUSE session
> Caused by:
> Operation not permitted (os error 1)
> Error: Failed to create mount process
> ```
> Please advise.
> Thanks!
> Matt

**Comment by larsks** [comment]
I'm pretty sure that Matt's surmise is correct: you cannot perform mount operations in a container without additional privileges. I think that granting `CAP_SYS_ADMIN` to the pod would be sufficient, but we would have to create a custom [SCC](https://docs.openshift.com/container-platform/4.16/authentication/managing-security-context-constraints.html) for that. It would be easier just to grant access to the `privileged` SCC via the `system:openshift:scc:privileged` ClusterRole.

We can do that by adding a ClusterRoleBinding like:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-allow-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  namespace: some-project
  name: some-service-account-name
```

With this in place -- and the annotation that Matt is already using which exposes `/dev/fuse` inside the pod -- things work as expected.
