### ISSUE TITLE
Cluster-wide enabled monitoring of user workloads not working

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#712]
Unfortunately the issue persists.
Same yaml supplied via web ui

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: rclone-app
  name: rclone-app
spec:
  endpoints:
  - interval: 30s
    port: 5572
    scheme: http
    path: /metrics
  selector:
    matchLabels:
      app: rclone-app
```

Output:
```
Danger alert:An error occurred

servicemonitors.monitoring.coreos.com is forbidden: User
"esarmien@hmdc.harvard.edu" cannot create resource "servicemonitors"
in API group "monitoring.coreos.com" in the namespace
"iqss-rc-infrastructure-for-social-scientists-061af7"
```
