### ISSUE TITLE
OpenShift Virtualization testing—VM SSH access

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#724]
https://docs.openshift.com/container-platform/4.15/virt/virtual_machines/virt-accessing-vm-ssh.html

**Comment by naved001** [comment]
SSH access over what network? some public floating IP or just with virtctl ssh

**Comment by jtriley** [comment]
> SSH access over what network? some public floating IP or just with virtctl ssh

The latter given that it's more secure (goes through OpenShift API and uses node port forwarding) and isn't exposing SSH to the public.

**Comment by schwesig** [comment]
https://docs.openshift.com/container-platform/4.15/virt/virtual_machines/virt-accessing-vm-ssh.html

**Comment by joachimweyl** [comment]
@schwesig please provide an update on how SSH testing is going.

**Comment by schwesig** [comment]
@joachimweyl I did some first trial and error but couldn't finish/produce anything useful; some other topics came in.
It needs to be stretched into the next sprint.

**Comment by schwesig** [comment]
going over to
- https://github.com/nerc-project/operations/issues/709

**Comment by joachimweyl** [comment]
@schwesig is this issue resolved? I don't see any resolution comments.

**Comment by schwesig** [comment]
from what I understood in one of the meeting, this was tested and approved.
Therefore I added the comment "going over to documentation".
From my understanding it now needs to be documented?

But maybe I am wrong?

**Comment by computate** [comment]
This has been tested. A couple things to keep in mind for VM ssh access: 

```yaml
spec:
  template:
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: computate-ssh
```

- The `accessCredentials` section needs to be defined when the VirtualMachine is created. 


```bash
(python) [ctate@tower1 ai-telemetry]$ virtctl ssh vm/computate-vm-gpu
ctate@vm/computate-vm-gpu.virt-test's password: 
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Thu Feb 27 12:34:22 2025 from 10.128.2.32
```
