### ISSUE TITLE
OpenShift Virtualization testing—publicly expose non-http services

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#728]
- starting point https://docs.openshift.com/container-platform/4.15/virt/vm_networking/virt-networking-overview.html
  - centOS stream 9 VM, expose postgres externally (non HTTP service)
    - best: with end to end TLS & security
 - kafka
 - postgres
 - ...

**Comment by computate** [comment]
I will be working on it this week.

**Comment by computate** [comment]
I added the following template label to my VirtualMachine `oc -n virt-test get vm/computate-centos-stream9` for service support for my postgresql server. 
```yaml
spec:
  template:
    metadata:
      labels:
        kubevirt.io/domain: computate-centos-stream9
```

**Comment by computate** [comment]
Update your postgresql pg_hba.conf file to allow md5 password access to external users. 

```bash
sudo vim /var/lib/pgsql/data/pg_hba.conf
host all all 0.0.0.0/0 md5
:wq
sudo systemctl restart postgresql
```

**Comment by computate** [comment]
```yaml
apiVersion: v1
kind: Service
metadata:
  name: computate-postgres-test
  namespace: virt-test
spec:
  selector:
    computate-postgres-test: 'true' 
  type: NodePort 
  ports: 
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
```

Notes: 
- When creating a service, be sure to keep it within the following nodePort numbers: `The range of valid ports is 30000-32767" for field "spec.ports[0].nodePort".`
- If you're VM is running when you add the template label, stop and start your VM.
