### ISSUE TITLE
feat: obs.nerc automate renewal of certs and keys for observability/grafana

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#802]
follow up/ connected to - https://github.com/nerc-project/operations/issues/801
# feat: obs.nerc automate renewal of certs and keys for observability/grafana

## Motivation
Certificate and key renewal for the observability component in the NERC OpenShift environment requires manual intervention.
Automating this process would reduce downtime, ensuring consistent security for Grafana.

## Completion Criteria
- An automated solution is identified and tested
- Solution integrates within NERC infrastructure; no/minimal manual work needed
- tested and long-term verification

## Description
- [ ] Identify solutions for auto-renewal of `observability-grafana-certs` and `observability-server-ca-certs`
- [ ] Implement the selected solution
- [ ] Document the automated renewal process for future reference
- [ ] Set reminder issue to check and intervene if needed on the next renewal date
  - [ ] create follow-up issue

## Completion Dates
- Desired: 2025-08-01
- Required: 2025-02-01

**Comment by morantara** [comment]
@schwesig will this get done in this sprint? should it be pushed to a future sprint?

**Comment by schwesig** [comment]
should fix the repeating #801

**Comment by morantara** [comment]
@schwesig do you think this will be completed this sprint or should we push it to a future sprint?

**Comment by morantara** [comment]
@schwesig should this be pushed to a future sprint?

**Comment by computate** [comment]
Closing this MOC 1.0 issue, because MOC 1.0 will be shut down and we won't be able to do this vault push integration, and AI Telemetry is not a feature of MOC 2.0.

**Comment by schwesig** [comment]
it happened again :) 2026-08-12, cert expired, central datasource on obs Grafana dead, all hub dashboards dark. Same movie as #800 in 2024.

Fixed manually again, fresh cert from the hub secret observability-grafana-certs into Vault nerc/nerc-ocp-obs/dex/grafanas, ESO synced it, restarted grafana.

Interesting: ACM rotates its own cert automatically, the fresh one was sitting on the hub since end of May.
Everything is automated except the one manual copy step from hub to Vault.

Idea for next time we need it... MOC 2.0?
- A: PushSecret on the hub (the idea from the comment above, thanks Chris): push tls.crt/tls.key to an own Vault path, obs ExternalSecret picks it up from there. BUT, **Needs one write approle scoped to that path**. No humans involved anymore.
- B: backstop alert: x509-certificate-exporter on the secret plus a rule, warning at 30d, critical at 7d, fallback procedure in the annotations. Rules are written and promtool validated already.

**Comment by schwesig** [comment]
``` yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nerc-cert-expiry
  namespace: cert-exporter
  labels:
    nerc.mghpcc.org/component: cert-monitoring
spec:
  groups:
    - name: nerc-cert-expiry
      interval: 24h
      rules:
        - alert: GrafanaObservatoriumCertExpiringSoon
          expr: |
            (x509_cert_not_after{secret_namespace="grafana",
               secret_name="oauth-client-secret",
               secret_key="GF_TLSCLIENTCERT"}
             - time()) < 30 * 24 * 3600
          labels:
            severity: warning
          annotations:
            summary: >-
              Observatorium client cert in {{ $labels.secret_namespace }}/{{ $labels.secret_name }}
              expires in {{ $value | humanizeDuration }}
            description: >-
              mTLS client cert for the central Grafana datasource runs out soon.
              If the automation (PushSecret from the ACM hub to Vault) is brocken,
              this is the last warning before all hub dashboards go dark.
              Check: hub secret observability-grafana-certs has a fresh
              cert (ACM rotates ~2.5 months early); Vault nerc/nerc-ocp-obs/dex/grafanas
              has it too; ESO synced it.
        - alert: GrafanaObservatoriumCertExpiryCritical
          expr: |
            (x509_cert_not_after{secret_namespace="grafana",
               secret_name="oauth-client-secret",
               secret_key="GF_TLSCLIENTCERT"}
             - time()) < 7 * 24 * 3600
          labels:
            severity: critical
          annotations:
            summary: >-
              Observatorium client cert expires in {{ $value | humanizeDuration }}, act now
            description: >-
              Under 7 days left. Manual fallback procedure: copy tls.crt/tls.key from
              hub secret open-cluster-management-observability/observability-grafana-certs
              into Vault nerc/nerc-ocp-obs/dex/grafanas (GF_TLSCLIENTCERT/GF_TLSCLIENTKEY),
              then force sync the ExternalSecret oauth-client-secret in namespace grafana.
```

**Comment by schwesig** [comment]
``` yaml
# Runs in the grafana namespace, mounts ONLY the key
# GF_TLSCLIENTCERT from oauth-client-secret as a file, no Secrets-RBAC needed,
# the private key stays outside. kubelet pulls ESO updates automaticaly.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x509-certificate-exporter
  namespace: grafana
  labels:
    app.kubernetes.io/name: x509-certificate-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-certificate-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: x509-certificate-exporter
    spec:
      containers:
        - name: exporter
          image: enix/x509-certificate-exporter:3.19.1
          args:
            - --watch-file=/certs/GF_TLSCLIENTCERT
            - --listen-address=:9793
          ports:
            - {name: metrics, containerPort: 9793}
          volumeMounts:
            - {name: certs, mountPath: /certs, readOnly: true}
          resources:
            requests: {cpu: 10m, memory: 32Mi}
            limits: {memory: 64Mi}
      volumes:
        - name: certs
          secret:
            secretName: oauth-client-secret
            items:
              - {key: GF_TLSCLIENTCERT, path: GF_TLSCLIENTCERT}
---
apiVersion: v1
kind: Service
metadata:
  name: x509-certificate-exporter
  namespace: grafana
  labels:
    app.kubernetes.io/name: x509-certificate-exporter
spec:
  selector:
    app.kubernetes.io/name: x509-certificate-exporter
  ports:
    - {name: metrics, port: 9793, targetPort: 9793}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: x509-certificate-exporter
  namespace: grafana
  labels:
    app.kubernetes.io/name: x509-certificate-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-certificate-exporter
  endpoints:
    - port: metrics
      interval: 15m
      scrapeTimeout: 30s
```
