### ISSUE TITLE
OpenShift Virtualization: Update coldfront to create updated resourcequota for passthroughed GPUs.

### ISSUE THREAD

**Issue by naved001** [nerc-project/operations#820]
## Motivation

To offer GPUs in VMs in OpenShift virtualization we need to update coldfront to update resourcequotas for GPUs configured in PCI passthrough mode.

## Completion Criteria

We can enforce quotas on passthroughed GPUs.

## Description

When a GPU is configured in passthrough mode they show up as new allocatable resources. For instance, nvidia.com/A100_SXM4_40GB appears as a resource for A100 GPUs, and nvidia.com/GV100GL_Tesla_V100 for V100 GPUs. As a result, we will need to update the resource quotas for projects and adjust Coldfront configuration to manage access to these resources.

Original issue where this is discussed: https://github.com/nerc-project/operations/issues/725#issuecomment-2474796687

## Completion dates
Desired - 20YY-MM-DD
Required - TBD

**Comment by joachimweyl** [comment]
@naved001 if you need to leave before this is complete should we have a backup?

**Comment by naved001** [comment]
@joachimweyl I don't know the backup should be. This will most likely not get completed before I leave and for that reason I had not assigned this issue to myself; I only created it. 

Somebody with knowledge of openshift resourcequota should be able to update coldfront to handle this. After that we'll need to figure out the right prometheus query for billing purposes.

**Comment by naved001** [comment]
I tested that resourcequota works for these "new" GPU resources.

I created a resourcequota with the following specs that permit only a single A100.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: naved-sandbox-rq
  namespace: naved-sandbox
spec:
  hard:
    limits.cpu: "10"
    limits.ephemeral-storage: 60Gi
    limits.memory: 48Gi
    persistentvolumeclaims: "20"
    requests.nvidia.com/A100_SXM4_40GB: "1"
    requests.nvidia.com/GV100GL_Tesla_V100: "1"
    requests.nvidia.com/gpu: "0"
```

I could successfully launch a VM with 1 A100 but trying to use 2 A100 does not succeed as expected.

```
    message: 'failed to create virtual machine pod: pods "virt-launcher-naved-gpu-test-2-899c4"
      is forbidden: exceeded quota: naved-sandbox-rq, requested: requests.nvidia.com/A100_SXM4_40GB=2,
      used: requests.nvidia.com/A100_SXM4_40GB=0, limited: requests.nvidia.com/A100_SXM4_40GB=1'
```

So, ultimately what we will need to do is set `requests.nvidia.com/A100_SXM4_40GB` and `requests.nvidia.com/GV100GL_Tesla_V100` to `0` for all namespaces, and then only set it to a positive number where we want to permit GPU usage in a VM.
