### ISSUE TITLE
Get network stats in Observability

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#893]
## Motivation
There is a new network setup with 2x Cisco switches and 1x dell switch (both of which are top of rack NERC switches) with SNMP read only access for monitoring. We will add these metrics to Observability in the MOC.

**Comment by computate** [comment]
I'm not aware of a Red Hat Operator for switch observability, but Red Hat suggests we can use Checkmk: https://www.redhat.com/en/blog/switch-monitoring-checkmk
- We could run Checkmk as a container: https://docs.checkmk.com/latest/en/introduction_docker.html
- Integrate it with Prometheus: https://docs.checkmk.com/latest/en/monitoring_prometheus.html
- Set up metrics collection in OpenShift: https://docs.openshift.com/container-platform/4.8/monitoring/managing-metrics.html#setting-up-metrics-collection-for-user-defined-projects_managing-metrics

**Comment by joachimweyl** [comment]
@hakasapl please reach out to @computate when you are back and you can work on this together.

**Comment by computate** [comment]
@larsks suggested using this for SNMP metrics: https://github.com/prometheus/snmp_exporter

**Comment by computate** [comment]
@hakasapl mentioned that this will require setting up a VLAN for cluster access to the network for SNMP.

**Comment by computate** [comment]
A PR has been made for the VLAN: 
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/650

**Comment by hakasapl** [comment]
## Supported MIBs for Dell OS9
```
NERC-R2PCC21-SW-TORS#show snmp supported-mibs
MIB                                      OID
--------------------------------------------------------------
RFC1155-SMI                              -
RFC-1212                                 -
SNMPv2-SMI                               -
SNMPv2-TC                                -
SNMPv2-CONF                              -
INET-ADDRESS-MIB                         -
IANAifType-MIB                           -
IANA-ADDRESS-FAMILY-NUMBERS-MIB          -
IANA-RTPROTO-MIB                         -
IPV6-FLOW-LABEL-MIB                      -
SNMPv2-MIB                               1.3.6.1.2.1
IF-MIB                                   1.3.6.1.2.1.31
IP-MIB                                   1.3.6.1.2.1.48
TCP-MIB                                  1.3.6.1.2.1.49
UDP-MIB                                  1.3.6.1.2.1.50
RFC1213-MIB                              -
EtherLike-MIB                            1.3.6.1.2.1.35
SNMP-FRAMEWORK-MIB                       1.3.6.1.6.3.10
RADIUS-AUTH-CLIENT-MIB                   1.3.6.1.2.1.67.1.2
SNMP-MPD-MIB                             1.3.6.1.6.3.11
RMON-MIB                                 1.3.6.1.2.1.16
RFC1271-MIB                              -
TOKEN-RING-RMON-MIB                      1.3.6.1.2.1.16.1.2
RMON2-MIB                                1.3.6.1.2.1.16
HCNUM-TC                                 1.3.6.1.2.1.78
HC-RMON-MIB                              1.3.6.1.2.1.16.21
HC-ALARM-MIB                             1.3.6.1.2.1.16.29
SFLOW-MIB                                1.3.6.1.4.1.14706.1
ENTITY-MIB                               1.3.6.1.2.1.47
INTEGRATED-SERVICES-MIB                  1.3.6.1.2.1.52
DIFFSERV-DSCP-TC                         1.3.6.1.2.1.96
DIFFSERV-MIB                             1.3.6.1.2.1.97
IEEE8021-TC-MIB                          -
IEEE8021-PFC-MIB                         1.3.111.2.802.1.1.21
BRIDGE-MIB                               1.3.6.1.2.1.17
P-BRIDGE-MIB                             1.3.6.1.2.1.17.6
Q-BRIDGE-MIB                             1.3.6.1.2.1.17.7
LLDP-MIB                                 1.0.8802.1.1.2
LLDP-EXT-DOT1-MIB                        1.0.8802.1.1.2.1.5.3
LLDP-EXT-DOT3-MIB                        1.0.8802.1.1.2.1.5.4623
LLDP-EXT-MED-MIB                         1.0.8802.1.1.2.1.5.4795
LLDP-V2-TC-MIB                           1.3.111.2.802.1.1.12
LLDP-V2-MIB                              1.3.111.2.802.1.1.13
LLDP-EXT-DOT1-V2-MIB                     1.3.111.2.802.1.1.13.1.5.32962
LLDP-EXT-DOT1-DCBX-MIB                   1.3.111.2.802.1.1.13.1.5.32962.5
IP-FORWARD-MIB                           1.3.6.1.2.1.4.24
VRRP-MIB                                 1.3.6.1.2.1.68
OSPF-MIB                                 1.3.6.1.2.1.14
BGP4-MIB                                 1.3.6.1.2.1.15
ISIS-MIB                                 1.3.6.1.3.37
PIM-STD-MIB                              1.3.6.1.2.1.157
TUNNEL-MIB                               1.3.6.1.2.1.10.131
IPSEC-SPD-MIB                            1.3.6.1.2.1.153
IEEE8023-LAG-MIB                         1.2.840.10006.300.43
DELL-NETWORKING-SMI                      1.3.6.1.4.1.6027
DELL-NETWORKING-TC                       -
DELL-NETWORKING-CHASSIS-MIB              1.3.6.1.4.1.6027.3.26
DELL-NETWORKING-PRODUCTS-MIB             1.3.6.1.4.1.6027.4.1
DELL-NETWORKING-SYSTEM-COMPONENT-MIB     1.3.6.1.4.1.6027.3.7
DELL-NETWORKING-TRAP-EVENT-MIB           1.3.6.1.4.1.6027.3.6
DELL-NETWORKING-COPY-CONFIG-MIB          1.3.6.1.4.1.6027.3.5
DELL-NETWORKING-IF-EXTENSION-MIB         1.3.6.1.4.1.6027.3.11
DELL-NETWORKING-FIB-MIB                  1.3.6.1.4.1.6027.3.9
DELL-NETWORKING-FPSTATS-MIB              1.3.6.1.4.1.6027.3.27
DELL-NETWORKING-LINK-AGGREGATION-MIB     1.3.6.1.4.1.6027.3.2
DELL-NETWORKING-BGP4-V2-MIB              1.3.6.1.4.1.6027.20.1
DELL-NETWORKING-ISIS-MIB                 1.3.6.1.4.1.6027.3.18
DELL-NETWORKING-FIPSNOOPING-MIB          1.3.6.1.4.1.6027.3.22
DELL-NETWORKING-VIRTUAL-LINK-TRUNK-MIB   1.3.6.1.4.1.6027.3.17
DELL-NETWORKING-DCB-MIB                  1.3.6.1.4.1.6027.3.15
DELL-NETWORKING-OPENFLOW-MIB             1.3.6.1.4.1.6027.3.20
DELL-NETWORKING-BMP-MIB                  1.3.6.1.4.1.6027.3.23
DELL-NETWORKING-MAC-NOTIFICATION-MIB     1.3.6.1.4.1.6027.3.28
DELL-NETWORKING-SYSLOG-MIB               1.3.6.1.4.1.6027.3.30
Dell-Vendor-MIB                          1.3.6.1.4.1.674.10895.3000
OSPFV3-MIB                               1.3.6.1.2.1.191
DELL-NETWORKING-PORT-SECURITY-MIB        1.3.6.1.4.1.6027.3.31
```

## Supported MIBs for Cisco NXOS
[List Here](https://cisco.github.io/cisco-mibs/supportlists/nexus9000/Nexus9000MIBSupportList.html)

**Comment by hakasapl** [comment]
Metrics I would be interested in as a network admin:
* Device hostname
* Interface up/down status
    * Would be nice to tie this to alert manager so we get notified if certain links go down
* Link utilization and Total capacity (so you can get a utilization %)
    * This is the most interesting to me because then we can build a weathermap to observe where links might need to be upgraded.
* Error/discard counters for each interface
* Light levels for optical transceivers (rx/tx)
    * Also any alarms for those optics (usually they have a high rx and low rx alarm)
* LLDP info, if any, from any adjacent devices
    * could one day allow us to dynamically map stuff out, assuming everything has lldp enabled
* spanning tree root interface / root IDs
* Power consumption (not sure if the switch reports this, but if it does I'm sure researchers would be interested)

This should be a good start, I will look through the MIBs sometime soon to see what else is useful to me

**Comment by computate** [comment]
Adding some notes. 

```bash
$ oc --as system:admin -n snmp-exporter debug
sh-4.4# yum install -y net-snmp-utils
snmpwalk -c public 10.82.3.41 -v 2c
snmpwalk -c public 10.82.3.42 -v 2c
```

**Comment by computate** [comment]
@larsks or @hakasapl do you know a sane way of obtaining the mibs we need? I am new to this, and so far I think i'm pretty close with this: 

```bash
install -d ~/.local/share/snmp-config/
install -d ~/.local/share/snmp-mibs/
install -d ~/.local/share/snmp/
install -d ~/.local/share/snmp-mibs/iana
install -d ~/.local/share/snmp-mibs/rfc
install -d ~/.local/share/snmp-mibs/dell
install -d ~/.local/share/snmp-mibs/docs
git clone https://github.com/cisco/cisco-mibs.git ~/.local/share/snmp-mibs/cisco-mibs
git clone https://github.com/hardaker/net-snmp.git ~/.local/share/snmp-mibs/net-snmp
git clone https://github.com/rlaager/docsis.git ~/.local/share/snmp-mibs/docs
git clone https://github.com/Poil/MIBs.git ~/.local/share/snmp-mibs/poil
curl https://www.iana.org/assignments/ianaprinter-mib/ianaprinter-mib -o ~/.local/share/snmp-mibs/iana/ianaprinter-mib.my
curl https://www.iana.org/assignments/ianacharset-mib/ianacharset-mib -o ~/.local/share/snmp-mibs/iana/ianacharset-mib.my
curl https://www.ndt-inc.com/SNMP/RFCs/rfc1513.mib -o ~/.local/share/snmp-mibs/rfc/rfc1513.mib
curl https://www.ndt-inc.com/SNMP/RFCs/rfc1493.mib -o ~/.local/share/snmp-mibs/rfc/rfc1493.mib
curl https://supportkb.dell.com/attachment/ka02R000000I7TFQA0/Current_MIBs_pkb_en_US_1.tar -o /tmp/Current_MIBs_pkb_en_US_1.tar
tar xvf /tmp/Current_MIBs_pkb_en_US_1.tar -C ~/.local/share/snmp-mibs/dell/

podman run --rm -it --entrypoint /bin/bash -v ~/.local/share/snmp-config:/config -v ~/.local/share/snmp-mibs:/mibs -v ~/.local/share/snmp:/snmp --privileged quay.io/prometheus/snmp-generator:v0.28.0

/bin/generator generate --generator-path=/config/generator.yml --output-path=/snmp -m /mibs/cisco-mibs -m /mibs/iana -m /mibs/rfc -m /mibs/net-snmp/mibs -m /mibs/cisco-mibs/v1 -m /mibs/cisco-mibs/v2 -m /mibs/dell -m /mibs/docs/mibs
```

But I seem to still be missing these and I'm not sure of the right place to find them. They seem to be dependencies of the Cisco MIBs. 

```bash
root@878bf83a60ed:/opt# /bin/generator generate --generator-path=/config/generator.yml --output-path=/snmp -m /mibs/cisco-mibs -m /mibs/iana -m /mibs/rfc -m /mibs/net-snmp/mibs -m /mibs/cisco-mibs/v1 -m /mibs/cisco-mibs/v2 -m /mibs/dell -m /mibs/docs/mibs
time=2025-02-20T20:38:52.376Z level=INFO source=net_snmp.go:174 msg="Loading MIBs" from=/mibs/cisco-mibs:/mibs/iana:/mibs/rfc:/mibs/net-snmp/mibs:/mibs/cisco-mibs/v1:/mibs/cisco-mibs/v2:/mibs/dell:/mibs/docs/mibs
time=2025-02-20T20:38:54.114Z level=WARN source=main.go:179 msg="NetSNMP reported parse error(s)" errors=181
time=2025-02-20T20:38:54.114Z level=ERROR source=main.go:185 msg="Missing MIB" mib=DNS-SERVER-MIB from="At line 36 in /mibs/cisco-mibs/v2/CISCO-DIST-DIRECTOR-MIB.my"
time=2025-02-20T20:38:54.114Z level=ERROR source=main.go:185 msg="Missing MIB" mib=RFC1493 from="At line 17 in /mibs/cisco-mibs/v1/CISCO-TS-STACK-MIB.my"
time=2025-02-20T20:38:54.114Z level=ERROR source=main.go:185 msg="Missing MIB" mib=RFC-1513 from="At line 29 in /mibs/cisco-mibs/v1/CISCO-TS-STACK-MIB.my"
time=2025-02-20T20:38:55.130Z level=ERROR source=main.go:137 msg="Failing on reported parse error(s)" help="Use 'generator parse_errors' command to see errors, --no-fail-on-parse-errors to ignore"
```

**Comment by computate** [comment]
I'm working with a `~/.local/share/snmp-config/generator.yml` that looks like this: 

```yaml
---
auths:
  public_v1:
    version: 1
  public_v2:
    version: 2

modules:

# Printer: RFC 3805
#
# https://tools.ietf.org/html/rfc3805
# https://www.iana.org/assignments/ianaprinter-mib/ianaprinter-mib.xhtml
  printer_mib:
    walk:
      - prtGeneralReset
      - prtConsoleDisable
      - prtGeneralPrinterName
      - prtGeneralSerialNumber
      - prtAlertCriticalEvents
      - prtAlertAllEvents
      - prtCoverStatus
      - prtMarkerLifeCount
      - prtMarkerPowerOnCount
      - prtMarkerSuppliesDescription
      - prtMarkerSuppliesLevel
      - prtMarkerSuppliesMaxCapacity
      - prtMarkerSuppliesType
    lookups:
      - source_indexes: [hrDeviceIndex, prtMarkerSuppliesIndex]
        lookup: prtMarkerSuppliesType

  cisco_device:
    walk:
      - CISCO-PROCESS-MIB::cpmProcessTimeCreated
      - CISCO-PROCESS-MIB::cpmCPUTotal1minRev
      - CISCO-PROCESS-MIB::cpmCPUTotal5minRev
      - CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolUsed
      - CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolFree
      - CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolType
      - CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolName
    lookups:
      - source_indexes: [entPhysicalIndex]
        lookup: CISCO-ENTITY-SENSOR-MIB::entSensorScale
      - source_indexes: [entPhysicalIndex]
        lookup: CISCO-ENTITY-SENSOR-MIB::entSensorType
      - source_indexes: [entPhysicalIndex]
        lookup: ENTITY-MIB::entPhysicalName
      - source_indexes: [ciscoMemoryPoolType]
        lookup: ciscoMemoryPoolName
      - source_indexes: [cempMemPoolIndex]
        lookup: cempMemPoolType
      - source_indexes: [cempMemPoolIndex]
        lookup: cempMemPoolName
    overrides:
      entSensorScale:
        ignore: true
      entSensorType:
        ignore: true
      entSensorValueTimeStamp:
        ignore: true
      entSensorValueUpdateRate:
        ignore: true
      entSensorMeasuredEntity:
        ignore: true
      ciscoMemoryPoolType:
        type: EnumAsInfo
        ignore: true
      cefcFRUPowerOperStatus:
        type: EnumAsStateSet
      ciscoMemoryPoolName:
        type: DisplayString
        ignore: true
      cempMemPoolName:
        type: DisplayString

  cisco_fc_fe:
    walk:
      - CISCO-FC-FE-MIB::fcIfInvalidCrcs
      - CISCO-FC-FE-MIB::fcIfFramesDiscard
      - CISCO-FC-FE-MIB::fcIfInvalidTxWords
      - CISCO-FC-FE-MIB::fcHCIfBBCreditTransistionToZero
      - CISCO-FC-FE-MIB::fcHCIfBBCreditTransistionFromZero
      - CISCO-FC-FE-MIB::fcIfTxWtAvgBBCreditTransitionToZero
      - CISCO-FC-FE-MIB::fcIfTxWaitCount
      - CISCO-FC-FE-MIB::fcIfCurrRxBbCredit
      - CISCO-FC-FE-MIB::fcIfCurrTxBbCredit

# Dell OpenManage MIBs
  dell:
    walk:
      - 1.3.6.1.4.1.674.10892.5.2 # statusGroup
      - 1.3.6.1.4.1.674.10892.5.4 # systemDetailsGroup
      - 1.3.6.1.4.1.674.10892.5.5 # storageDetailsGroup
# Dell network (Force10)
  dell_network:
    walk:
      - DELL-NETWORKING-CHASSIS-MIB::dellNetCpuUtilTable
      - DELL-NETWORKING-CHASSIS-MIB::dellNetPowerSupplyTable
      - DELL-NETWORKING-CHASSIS-MIB::dellNetSwModuleTable
      - DELL-NETWORKING-CHASSIS-MIB::dellNetFlashStorageTable
    overrides:
      dellNetPowerSupplyIndex:
        ignore: true
      dellNetFanDeviceType:
        type: EnumAsInfo
      dellNetPowerDeviceType:
        type: EnumAsInfo
      dellNetProcessorDeviceType:
        type: EnumAsInfo
```
