### ISSUE TITLE
New taints causing nvidia-gpu-operator DaemonSets from running on GPU nodes

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#913]
## Motivation
I was trying to get the [IBM Autopilot GPU health checks](https://console-openshift-console.apps.ocp-test.nerc.mghpcc.org/k8s/ns/autopilot/daemonsets/autopilot/pods) working again in the `nerc-ocp-test` cluster, but the pods would never receive the NVIDIA drivers correctly and the `nvidia-smi` command in the pod. I tested deploying Autopilot to the new `albany` cluster where we don't have any GPU taints, and Autopilot ran just fine in `albany`. So in`nerc-ocp-test` I deleted all of the pods in the `nvidia-gpu-operator` namespace and none of them came back up except one `gpu-operator-8479b7b55b-6bnpx`. I found out that there is a way to configure tolerations on the `ClusterPolicy/gpu-cluster-policy`: 

```yaml
spec:
  daemonsets:
    tolerations: 
    - effect: NoSchedule 
      key: nvidia.com/gpu.product 
      operator: Equal 
      value: NVIDIA-A100-SXM4-40GB 
    - effect: NoSchedule 
      key: nvidia.com/gpu.product 
      operator: Equal 
      value: Tesla-V100-PCIE-32GB 
```

This allowed the nvidia-gpu-operator pods to start, but not come to a running state because `autoUpgrade: false`. 

![Image](https://github.com/user-attachments/assets/c6841184-9485-4899-b9af-d126b453fd3e)

## Completion Criteria
Apply tolerations to the `ClusterPolicy/gpu-cluster-policy` and drain those nodes in the `nerc-ocp-test` cluster. 

## Description

By pausing autosync in ArgoCD for the `nvidia-gpu-operator-test` Application, and applying these temporary changes to the `ClusterPolicy/gpu-cluster-policy` in `nerc-ocp-test`, I believe it will resolve the issue. I think this problem also affects `nerc-ocp-prod` and it's GPU nodes, but that will have to wait for a maintenance window. 

```yaml
    manager:
      env:
      - name: ENABLE_GPU_POD_EVICTION
        value: "true"
      - name: ENABLE_AUTO_DRAIN
        value: "true"
      - name: DRAIN_USE_FORCE
        value: "true"
      - name: DRAIN_DELETE_EMPTYDIR_DATA
        value: "true"
    upgradePolicy:
      autoUpgrade: false
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
```
