### ISSUE TITLE
OpenShift Virtualization: Tolerations for GPU VMs

### ISSUE THREAD

**Issue by naved001** [nerc-project/operations#940]
## Motivation
When a VirtualMachine resource is created, it creates a corresponding virt-launcher-* pod that requests the necessary resources (CPU, VM, GPUs) for the VM. We'll need to figure out how to add taint toleration on these launcher pods.

## Completion Criteria
Test if tolerations will solve the issue and implement this feature to add tolerations to the VM resources.

## Description
- [ ] Test
- [ ] If it works in testing implement the fix

## Completion dates
Desired - 2025-03-19
Required - TBD

**Comment by naved001** [comment]
@dystewart According to [the docs](https://kubevirt.io/user-guide/compute/node_assignment/#taints-and-tolerations), it looks like we can set the tolerations when we create a VirtualMachineInstance resource. 

I guess if we could just go through the motions and test it we can close this issue then.

**Comment by naved001** [comment]
I tested that if I apply toleration for some arbitrary taint to the VirtualMachine definition then the virt-launcher pods correctly inherited those and my VM was scheduled on the tainted host. 

On the test cluster I noticed that wrk-2 is ready but has scheduling disabled (it's trying to reboot to apply a machineconfig)

```
➜  ~ oc get nodes wrk-2
NAME    STATUS                     ROLES    AGE    VERSION
wrk-2   Ready,SchedulingDisabled   worker   214d   v1.30.7
```

Which means it had the taint `node.kubernetes.io/unschedulable` 

So, if force my VM to run on it by specifying `nodeSelector: wrk-2` it fails to run

```
➜  virtualization git:(main) ✗ oc get vm -n naved-sandbox
NAME                     AGE     STATUS               READY
naved-containerdisk-64   3m15s   ErrorUnschedulable   False
```

But I then added the toleration and then it was scheduled.

```
    spec:
      nodeSelector:
        kubernetes.io/hostname: wrk-2
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
```
Here's the generated pod's definition including the toleration I added
```
➜  virtualization git:(main) ✗ oc get pod virt-launcher-naved-containerdisk-64-rp5px -o yaml |grep tolerations -A4
  tolerations:
  - key: node.kubernetes.io/unschedulable
    operator: Exists
```
