### ISSUE TITLE
OpenShift Virtualization: Document resource overhead when creating virtual machines

### ISSUE THREAD

**Issue by naved001** [nerc-project/operations#941]
When we create virtual machines, I have noticed that there's some overhead in CPU and memory. 

For a VM that I launched using containerdisk it was 10mili CPU, for some other VMs I noticed it be 100mili CPU (I think those were launched from a datavolume not sure why it makes a difference).  For memory I noticed an overhead of 300-400 MiB. 

The impact is that, if a project's resourcequota is 1 CPU they will NOT be able to launch a VM with 1 CPU (it'll have to be less like 990m CPU or 900m CPU) or their quota must be higher to accommodate the overhead. 

We need to investigate this more to get more concrete numbers.

**Comment by naved001** [comment]
I created some test VMs and what I noticed is that if you boot from a datavolume (probably most use cases) then there's no weird CPU overhead. But if you boot from a container disk then there's 10mili CPU overhead. 

Overall, I think we may simply say that "there may be some overheads in certain cases, please read the kubevirt docs". 


Memory overhead is always there and [the documentation](https://kubevirt.io/user-guide/compute/resources_requests_and_limits/#memory-requests-on-the-container) says the following:

> A calculated amount of overhead will be added to it, forming the memory request value for the container.

I noticed it being a few hundred MiBs over what is in the request.

Some scenarios I tested: 

1. When I launch a VM from a containerdisk then it consumes 10m CPU extra. The configuration looks like:
```
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinit
          rng: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/centos-stream:9
        name: containerdisk
```

It directly boots from this containerdisk, and if you reboot you lose all changes you make. I suspect a lot of folks will not use this.

2. When I launch a volume from a datavolume and if I specify the CPU resource requests then it consumes exactly what I requested, otherwise it'll request 100m CPU.

The relevant config looks like this
```
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        machine:
          type: pc-q35-rhel9.4.0
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: fedora-dv
        name: datavolumedisk1
```

Note that this datavolume was created because my virtualmachine definition pointed to a qcow image on the internet which is downloaded and then a datavolume is created. To do that it spins up a pod and the pod exists when the data volume is available.

```
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: fedora-dv 
    spec:
      storage:
        resources:
          requests:
            storage: 17Gi
        storageClassName: ocs-external-storagecluster-ceph-rbd
      source:
        http:
          url: "https://download.fedoraproject.org/pub/fedora/linux/releases/41/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2"
    status: {}
```
