### ISSUE TITLE
Document OpenTelemetry OIDC tenant authentication and authorization

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#946]
## Motivation
Document how we might implement OpenTelemetry multi-tenancy with OIDC providers like Dex and Keycloak.

**Comment by knikolla** [comment]
This is related to 

- https://github.com/nerc-project/operations/issues/948

**Comment by dheerajodha** [comment]
To [enable multi-tenancy with OIDC providers](https://grafana.com/docs/tempo/latest/setup/operator/multitenancy/#oidc-authentication-with-static-rbac) like Dex and Keycloak within your TempoStack CR's definition, add the `tenant` field, where
* `tenantName` and `tenantId` would point to the name of the tenant (Example: `cluster-nerc-ocp-prod`) you have defined.
* `issuerURL` points to the URL of the OIDC provider you're using. (see the "issuer" field [here](https://keycloak.apps.obs.nerc.mghpcc.org/realms/NERC/.well-known/openid-configuration))
* `redirectURL` points to the service that lets us access the Tempo instance and which exposes OpenTelemetry gRPC (OTLP) for trace ingestion (not sure what this should be; it needs to be figured out. Could it be collector or querier or? ---- something like that)
* `usernameClaim: preferred_username`
* secret.name: name of the secret (example `opentelemetry-tenant-cluster-nerc-ocp-prod`) which you've created in the cluster with the command
```
oc --as system:admin create secret generic opentelemetry-tenant-cluster-nerc-ocp-prod --from-literal=clientID=opentelemetry --from-literal=clientSecret=ZnQ-your-secret-goes-here-eSJRq
```
 >  where `clientID` points to the name of the client you created on Keycloak, and `clientSecret` points to the generated secret.
* authorization.roleBindings.name: points to the name of the auto-created serviceaccount on Keycloak

Finally, `spec.tenants` field should look something like this:
```
tenants:
    mode: static
    authentication:
      - tenantName: cluster-nerc-ocp-prod
        tenantId: cluster-nerc-ocp-prod
        oidc:
          issuerURL: https://keycloak.apps.obs.nerc.mghpcc.org/realms/NERC
          redirectURL: http://tempo-opentelemetry-querier.opentelemetry.svc:3200/oidc/cluster-nerc-ocp-config/callback
          usernameClaim: preferred_username
          secret:
            name: opentelemetry-tenant-cluster-nerc-ocp-prod
    authorization:
      roleBindings:
      - name: "service-account-opentelemetry"
        roles:
        - read-write
        subjects:
        - kind: user
          name: service-account-opentelemetry
      roles:
      - name: read-write
        permissions:
        - read
        - write
        resources:
        - traces
        tenants:
        - cluster-nerc-ocp-prod
```

After enabling this, when we sent traces data to Tempo from our sample application and tried to view the traces on Tempo UI, we saw the following error:

![Image](https://github.com/user-attachments/assets/f0cedb7e-49ca-42a8-9172-a4add452f82d)

We think this is because Grafana uses Dex, and we use Keycloak as our OIDC provider.
