### ISSUE TITLE
Document OpenAPI security spec for OpenID with Keycloak in AI Telemetry app

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#989]
## Motivation
Kristi and others would like to learn more about standards for OpenAPI specs using OpenID Connect Authentication like Keycloak in their APIs.

**Comment by morantara** [comment]
@computate should this be moved to a future sprint?

**Comment by computate** [comment]
Yes, can we move to June 2025 please?

**Comment by morantara** [comment]
@computate should this be pushed out a bit?

**Comment by computate** [comment]
Here is some basic documentation about this. I don't think this is a priority for MOC 2.0. 

## OpenAPI specs with OpenID and Keycloak

Explaining how Open APIs are access controlled by OpenID Connect standards within the AI Telemetry application. 

OpenAPI specifications that support OpenID Connect declare security first in the whole application. 
OpenAPI specs with security defined force users and service accounts through an authentication workflow before accessing the API. 

The `securitySchemes:` section of the OpenAPI spec should declare an `openIdConnect` scheme, 
with `type: openIdConnect`, 
and `openIdConnectUrl: https://keycloak.apps.obs.nerc.mghpcc.org/realms/NERC/.well-known/openid-configuration`
pointing to the openid-configuration for the right realm of the Keycloak application. 

```yaml
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://keycloak.apps.obs.nerc.mghpcc.org/realms/NERC/.well-known/openid-configuration') }}
```

Each secure API should define a <kbd>security:</kbd> section, 
with the name of the security scheme <kbd>openIdConnect:</kbd>, 
and the required scopes for the application, which should at least include <kbd>openid</kbd> and <kbd>profile</kbd> scopes, and any other scopes used by the application that retrieves additional information about the user for business logic. 

```yaml
    get:
      security:
        - openIdConnect:
          - openid
          - profile
```

Only authentication is performed on secured APIs in OpenAPI specs. 
Authorization of resources after authentication, like role-based access control and fine-grained access control, is not configured in security specs in OpenAPI specs.
