### ISSUE TITLE
Test GPU passthrough with H100

### ISSUE THREAD

**Issue by naved001** [nerc-project/operations#997]
There are 2 H100 nodes in the test cluster. We should test that PCI passthrough with H100 GPUs works as expected.

**Comment by naved001** [comment]
I have PR that configures them here: https://github.com/OCP-on-NERC/nerc-ocp-config/pull/671

**Comment by Milstein** [comment]
I tested using this code:
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
      command: ["sleep"]
      args: ["infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
```

Need to add GPU Accelerator Profile similar to [this](https://nerc-project.github.io/nerc-docs/openshift/applications/scaling-and-performance-guide/#how-to-specify-pod-to-use-gpu) that need to available on both OpenShift and RHOAI workbench and Model server setup.
